### ISSUE TITLE
First Prototype Changes

### ISSUE THREAD

**Issue by JasonLin43212** [JasonLin43212/Heist#19]
- [x] Make cameras easier to click on
- [x] Make it so that you can click on the part of the camera that is inside a wall
- [x] Cameras look weird? The little dot is off-centered
- [x] You can run past camera if you are close enough (Maybe add a collider? But that doesn't really make sense. Should we just keep it like this?)
- [x] Guards walk through walls when trying to chase the player (Turning issue)
- [x] Guards walk through walls when going back after chasing the player.
- [x] Player is a bit hard to control. It feels like the player is moving a bit too fast and often, I run into the camera range and then just lose.
- [x] Unity Errors (it constantly repeats in the console)

**Comment by lilianluong** [comment]
guard problems should be mostly addressed by #20 
(turning around corners is still somewhat sketchy but idk what to do about that)

**Comment by lilianluong** [comment]
Can we please separate out these big issues into many smaller ones
