### ISSUE TITLE
Checkpoint/Guard error

### ISSUE THREAD

**Issue by ssesena** [JasonLin43212/Heist#74]
Through play testing, I found a KeyError in SaveUtils. This error appears to happen after you hit a checkpoint and die.

![SaveUtilsBug](https://user-images.githubusercontent.com/66855001/166112280-18d9edef-ceb2-4fba-be11-5f103a91c6d8.PNG)

After a while of playing, if you die, you eventually get an error that prevents you from restarting the game. It is an IndexOutOfBounds error.

![GuardBehaviorBug](https://user-images.githubusercontent.com/66855001/166112321-9fde0647-3dc6-40bd-a47a-5b45019fa50f.PNG)

**Comment by lilianluong** [comment]
Bug task list as of 10pm 05/03 (continuously updating)

 - [x] checkpoint bug as above (saveutils x keycards)
 - [x] when shouting the guard moves towards the player through walls (note: colliders are inherited unintentionally) - COULD NOT REPRODUCE
 - [x] add more dialogue (-Andi)
